if(NOT DEFINED F2CPP_EXECUTABLE OR NOT DEFINED FIXTURE_DIR)
  message(FATAL_ERROR "CLI lifecycle test requires executable and fixtures")
endif()

string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(test_dir "$ENV{TMPDIR}/bellhop_f2cpp_cli_${suffix}")
if("$ENV{TMPDIR}" STREQUAL "")
  set(test_dir "/tmp/bellhop_f2cpp_cli_${suffix}")
endif()
file(MAKE_DIRECTORY "${test_dir}")
set(root "${test_dir}/case")

function(require_current_product expected_product)
  foreach(product shd ray arr)
    if("${product}" STREQUAL "${expected_product}")
      if(NOT EXISTS "${root}.${product}")
        message(FATAL_ERROR "missing expected .${product} output")
      endif()
      file(SIZE "${root}.${product}" product_size)
      if(product_size EQUAL 0)
        message(FATAL_ERROR "expected .${product} output is empty")
      endif()
    elseif(EXISTS "${root}.${product}")
      message(FATAL_ERROR "stale incompatible .${product} output was retained")
    endif()
    if(EXISTS "${root}.${product}.tmp")
      message(FATAL_ERROR "temporary .${product} output leaked after CLI run")
    endif()
  endforeach()
endfunction()

function(run_case fixture expected_product success_marker)
  file(COPY_FILE "${FIXTURE_DIR}/${fixture}" "${root}.env" ONLY_IF_DIFFERENT)
  file(WRITE "${root}.shd.tmp" "stale shd temporary output")
  file(WRITE "${root}.ray.tmp" "stale ray temporary output")
  file(WRITE "${root}.arr.tmp" "stale arr temporary output")
  execute_process(
    COMMAND "${F2CPP_EXECUTABLE}" "${root}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "CLI lifecycle run failed: ${stderr}")
  endif()
  require_current_product("${expected_product}")
  file(READ "${root}.prt" print_log)
  string(FIND "${print_log}" "${success_marker}" marker_index)
  if(marker_index EQUAL -1)
    message(FATAL_ERROR "success marker missing from PRT")
  endif()
endfunction()

function(require_parse_failure_preserves product)
  file(SHA256 "${root}.${product}" old_hash)
  file(WRITE "${root}.env" "invalid environment\n")
  execute_process(
    COMMAND "${F2CPP_EXECUTABLE}" "${root}"
    RESULT_VARIABLE failure_result
    OUTPUT_VARIABLE failure_stdout
    ERROR_VARIABLE failure_stderr)
  if(failure_result EQUAL 0)
    message(FATAL_ERROR "invalid ENV unexpectedly succeeded")
  endif()
  file(SHA256 "${root}.${product}" new_hash)
  if(NOT old_hash STREQUAL new_hash)
    message(FATAL_ERROR "failed run modified the previous valid .${product}")
  endif()
  foreach(candidate shd ray arr)
    if(EXISTS "${root}.${candidate}.tmp")
      message(FATAL_ERROR "failed CLI run leaked a .${candidate}.tmp output")
    endif()
  endforeach()
  file(READ "${root}.prt" failure_log)
  string(FIND "${failure_log}" "FATAL ERROR" fatal_index)
  if(fatal_index EQUAL -1)
    message(FATAL_ERROR "failed CLI run did not record FATAL ERROR")
  endif()
endfunction()

function(require_publish_failure_preserves old_product new_product)
  file(SHA256 "${root}.${old_product}" old_hash)
  file(MAKE_DIRECTORY "${root}.${new_product}")
  execute_process(
    COMMAND "${F2CPP_EXECUTABLE}" "${root}"
    RESULT_VARIABLE failure_result
    OUTPUT_VARIABLE failure_stdout
    ERROR_VARIABLE failure_stderr)
  if(failure_result EQUAL 0)
    message(FATAL_ERROR "blocked product publication unexpectedly succeeded")
  endif()
  file(SHA256 "${root}.${old_product}" new_hash)
  if(NOT old_hash STREQUAL new_hash)
    message(FATAL_ERROR "failed publication modified the prior .${old_product}")
  endif()
  if(EXISTS "${root}.${new_product}.tmp")
    message(FATAL_ERROR "failed publication leaked a .${new_product}.tmp output")
  endif()
  file(READ "${root}.prt" failure_log)
  string(FIND "${failure_log}" "FATAL ERROR" fatal_index)
  if(fatal_index EQUAL -1)
    message(FATAL_ERROR "failed publication did not record FATAL ERROR")
  endif()
  file(REMOVE_RECURSE "${root}.${new_product}")
endfunction()

run_case("cli_coherent.env" "shd" "Bellhop F2CPP completed successfully")
run_case("cli_ray.env" "ray" "Bellhop F2CPP ray trace completed successfully")
run_case("cli_arrival_ascii.env" "arr" "Bellhop F2CPP arrivals completed successfully")
file(READ "${root}.arr" ascii_prefix OFFSET 0 LIMIT 1 HEX)
if(NOT ascii_prefix STREQUAL "27")
  message(FATAL_ERROR "A mode did not produce an ASCII ARR product")
endif()
run_case("cli_eigenray_gaussian.env" "ray" "Bellhop F2CPP eigenray completed successfully")
run_case("cli_arrival_binary.env" "arr" "Bellhop F2CPP arrivals completed successfully")
file(READ "${root}.arr" binary_prefix OFFSET 0 LIMIT 4 HEX)
if(NOT binary_prefix STREQUAL "04000000")
  message(FATAL_ERROR "a mode did not produce GNU sequential-unformatted ARR")
endif()
run_case("cli_coherent.env" "shd" "Bellhop F2CPP completed successfully")
run_case("cli_eigenray_zero.env" "ray" "Bellhop F2CPP eigenray completed successfully")
require_parse_failure_preserves("ray")
run_case("cli_arrival_ascii.env" "arr" "Bellhop F2CPP arrivals completed successfully")
require_parse_failure_preserves("arr")
run_case("cli_coherent.env" "shd" "Bellhop F2CPP completed successfully")
require_parse_failure_preserves("shd")
file(COPY_FILE "${FIXTURE_DIR}/cli_arrival_ascii.env" "${root}.env" ONLY_IF_DIFFERENT)
require_publish_failure_preserves("shd" "arr")

file(REMOVE_RECURSE "${test_dir}")
